minApprovals:
  OWNER: 1
  
# must be enabled as a merge option in the repository settings
mergeMethod: squash

# report bot status details as a check on the PR
reportStatus: true

deleteBranchAfterMerge: true

blockingLabels:
- blocked
